|<h2>Course:</h2>|<h1><a href="https://udemy.com/course/deeplearning_x/?couponCode=202508" target="_blank">A deep understanding of deep learning</a></h1>|
|-|:-:|
|<h2>Section:</h2>|<h1>Math, numpy, pytorch<h1>|
|<h2>Lecture:</h2>|<h1><b>OMG it's the dot product!<b></h1>|

<br>

<h5><b>Teacher:</b> Mike X Cohen, <a href="https://sincxpress.com" target="_blank">sincxpress.com</a></h5>
<h5><b>Course URL:</b> <a href="https://udemy.com/course/deeplearning_x/?couponCode=202508" target="_blank">udemy.com/course/deeplearning_x/?couponCode=202508</a></h5>
<i>Using the code without the course may lead to confusion or errors.</i>

In [1]:
# import libraries
import numpy as np
import torch

# Using numpy

In [2]:
# create a vector
nv1 = np.array([1,2,3,4])
nv2 = np.array([0,1,0,-1])

# dot product via function
print(np.dot(nv1,nv2))

# dot product via computation
print(np.sum( nv1*nv2 ))

-2
-2


# Using pytorch

In [3]:
# create a vector
tv1 = torch.tensor([1,2,3,4])
tv2 = torch.tensor([0,1,0,-1])

# dot product via function
print(torch.dot(tv1,tv2))

# dot product via computation
print(torch.sum( tv1*tv2 ))

tensor(-2)
tensor(-2)


In [12]:
#Dot product represents commonality between two vectors/matrices (like images, corelation/covariance between data)
#Practice of dot product with matrices

tm1 = torch.tensor([[1,2,3,4],[1,2,3,4]])
tm2 = torch.tensor([[0,1,0,-1],[0,1,0,-1]])

#print(torch.dot(tm1,tm2)) #Error torch dot allows only 1D dot product
print(torch.sum(tm1*tm2))


nm1 = np.array([[1,2,3,4],[1,2,3,4]])
nm2 = np.array([[0,1,0,-1],[0,1,0,-1]])

#print(np.dot(nm1,nm2)) #Error numpy expects inner dimensions to be equal
print(np.sum(nm1*nm2))

#Use matmul function for torch and numpy to multiply
print(torch.matmul(tm1.T,tm2))
print(np.matmul(nm1.T,nm2))

tensor(-4)
-4
tensor([[ 0,  2,  0, -2],
        [ 0,  4,  0, -4],
        [ 0,  6,  0, -6],
        [ 0,  8,  0, -8]])
[[ 0  2  0 -2]
 [ 0  4  0 -4]
 [ 0  6  0 -6]
 [ 0  8  0 -8]]
