|<h2>Course:</h2>|<h1><a href="https://udemy.com/course/deeplearning_x/?couponCode=202508" target="_blank">A deep understanding of deep learning</a></h1>|
|-|:-:|
|<h2>Section:</h2>|<h1>Math, numpy, pytorch<h1>|
|<h2>Lecture:</h2>|<h1><b>Matrix multiplication<b></h1>|

<br>

<h5><b>Teacher:</b> Mike X Cohen, <a href="https://sincxpress.com" target="_blank">sincxpress.com</a></h5>
<h5><b>Course URL:</b> <a href="https://udemy.com/course/deeplearning_x/?couponCode=202508" target="_blank">udemy.com/course/deeplearning_x/?couponCode=202508</a></h5>
<i>Using the code without the course may lead to confusion or errors.</i>

In [1]:
# import libraries
import numpy as np
import torch

# Using numpy

In [2]:
# create some random matrices
A = np.random.randn(3,4)
B = np.random.randn(4,5)
C = np.random.randn(3,7)

# try some multiplications...
print(np.round( A@B   ,2)), print(' ')
# print(np.round( A@C   ,2)), print(' ')#Error: Inner dim do not match
# print(np.round( B@C   ,2)), print(' ')#Error: Inner dim do not match
print(np.round( C.T@A ,2))

[[ 1.19 -2.09 -1.81 -0.67  1.86]
 [-1.2  -0.1   0.53  0.2   1.01]
 [ 1.53  2.92  0.96 -2.24  2.89]]
 
[[ 0.28  0.59  1.98  1.05]
 [ 0.06 -1.37  0.77 -1.53]
 [-0.2   1.81 -2.58  2.63]
 [ 0.32 -0.92  1.87  0.13]
 [ 0.   -2.69  0.34 -2.93]
 [ 0.45  0.46  1.9   2.58]
 [ 0.54  0.06  3.5   1.38]]


# Using pytorch

In [3]:
# create some random matrices
A  = torch.randn(3,4)
B  = torch.randn(4,5)
C1 = np.random.randn(4,7)
C2 = torch.tensor( C1,dtype=torch.float )#Converting numpy array to torch tensor

# try some multiplications...
print(np.round( A@B   ,2)), print(' ')
# print(np.round( A@B.T ,2)), print(' ')#Error: Inner dim do not match
print(np.round( A@C1  ,2)), print(' ')#Torch tensor and numpy array types are compatible in this case but not always with all operations
print(np.round( A@C2  ,2))

tensor([[-1.9800,  3.2400,  1.6300,  0.8400,  1.9400],
        [ 1.5000, -0.7600,  0.5000, -0.0500, -0.6500],
        [-0.1200, -1.7800, -1.3800, -3.0800, -0.4800]])
 
tensor([[ 0.2700, -1.0100,  0.3300,  0.4900,  0.6600, -0.9500, -1.5400],
        [-1.5500, -0.7400,  2.1000, -1.5900,  0.3900,  1.9400,  0.7200],
        [ 1.0900,  2.0200, -2.4400,  3.0400, -0.6800,  1.0200,  2.4700]],
       dtype=torch.float64)
 
tensor([[ 0.2700, -1.0100,  0.3300,  0.4900,  0.6600, -0.9500, -1.5400],
        [-1.5500, -0.7400,  2.1000, -1.5900,  0.3900,  1.9400,  0.7200],
        [ 1.0900,  2.0200, -2.4400,  3.0400, -0.6800,  1.0200,  2.4700]])


/tmp/ipykernel_2315/3137305625.py:10: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  print(np.round( A@C1  ,2)), print(' ')#Torch tensor and numpy array types are compatible in this case but not always with all operations
