|<h2>Course:</h2>|<h1><a href="https://udemy.com/course/deeplearning_x/?couponCode=202508" target="_blank">A deep understanding of deep learning</a></h1>|
|-|:-:|
|<h2>Section:</h2>|<h1>Math, numpy, pytorch<h1>|
|<h2>Lecture:</h2>|<h1><b>Vector and matrix transpose<b></h1>|

<br>

<h5><b>Teacher:</b> Mike X Cohen, <a href="https://sincxpress.com" target="_blank">sincxpress.com</a></h5>
<h5><b>Course URL:</b> <a href="https://udemy.com/course/deeplearning_x/?couponCode=202508" target="_blank">udemy.com/course/deeplearning_x/?couponCode=202508</a></h5>
<i>Using the code without the course may lead to confusion or errors.</i>

In [1]:
# import libraries
import numpy as np
import torch

# Using numpy

In [4]:
# create a vector
nv = np.array([ [1,2,3,4] ])
print(nv), print(' ')

# transpose it
print(nv.T), print(' ')

# transpose the transpose!
nvT = nv.T
print(nvT.T)

#Another way to transpose
nv = np.array([ [1,2,3,4] ])
print(np.transpose(nv))

[[1 2 3 4]]
 
[[1]
 [2]
 [3]
 [4]]
 
[[1 2 3 4]]
[[1]
 [2]
 [3]
 [4]]


In [5]:
# repeat for a matrix
nM = np.array([ [1,2,3,4],
                [5,6,7,8]
               ])
print(nM), print(' ')

# transpose it
print(nM.T), print(' ')

# transpose the transpose!
nMT = nM.T
print(nMT.T)

[[1 2 3 4]
 [5 6 7 8]]
 
[[1 5]
 [2 6]
 [3 7]
 [4 8]]
 
[[1 2 3 4]
 [5 6 7 8]]


# Using pytorch

In [6]:
# create a vector
tv = torch.tensor([ [1,2,3,4] ])
print(tv), print(' ')

# transpose it
print(tv.T), print(' ')

# transpose the transpose!
tvT = tv.T
print(tvT.T)

tensor([[1, 2, 3, 4]])
 
tensor([[1],
        [2],
        [3],
        [4]])
 
tensor([[1, 2, 3, 4]])


In [7]:
# repeat for a matrix
tM = torch.tensor([ [1,2,3,4],[5,6,7,8] ])
print(tM), print(' ')

# transpose it
print(tM.T), print(' ')

# transpose the transpose!
tMT = tM.T
print(tMT.T)

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
 
tensor([[1, 5],
        [2, 6],
        [3, 7],
        [4, 8]])
 
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


In [14]:
#Practice

torch_row_vector = torch.tensor([[5,6,7,8]])
torch_col_vector = torch.tensor([[5],[6],[7],[8]])

numpy_row_vector = np.array([[5,6,7,8]])
numpy_col_vector = np.array([[5],[6],[7],[8]])

print(torch_row_vector)
print(torch_col_vector),print(' ')

print(numpy_row_vector)
print(numpy_col_vector),print(' ')

torch_col2 = torch.tensor([[1],[2],[3],[4]])
torch_matrix1 = torch.cat([torch_col_vector,torch_col2],dim=1)
torch_matrix2 = torch.cat([torch_col_vector,torch_col2])
print(torch_matrix1)
print(torch_matrix2)

tensor([[5, 6, 7, 8]])
tensor([[5],
        [6],
        [7],
        [8]])
 
[[5 6 7 8]]
[[5]
 [6]
 [7]
 [8]]
 
tensor([[5, 1],
        [6, 2],
        [7, 3],
        [8, 4]])
tensor([[5],
        [6],
        [7],
        [8],
        [1],
        [2],
        [3],
        [4]])


In [8]:
# examine data types
print(f'Variable nv is of type {type(nv)}')
print(f'Variable nM is of type {type(nM)}')
print(f'Variable tv is of type {type(tv)}')
print(f'Variable tM is of type {type(tM)}')


Variable nv is of type <class 'numpy.ndarray'>
Variable nM is of type <class 'numpy.ndarray'>
Variable tv is of type <class 'torch.Tensor'>
Variable tM is of type <class 'torch.Tensor'>
